### ISSUE TITLE
Id-Fixer Scrambled ids on client

### ISSUE THREAD

**Issue by Gargule** [desagas/Biome-Id-Fixer#11]
From where this mod picks biome IDs? Our server got scrambled IDs after adding bunch of biome mods but our clients doesn't. Then we installed Id-Fixer and strange thing happened. Client also got scrambled. But removing mod from client returned correct ids. And in level.dat all IDs was correct both on server and client. So i want to know where Minecraft (or Forge) stores these wrong IDs that somehow used by server but not by client. ("Wrong" IDs from server and client was same)

_Originally posted by @Gargule in https://github.com/desagas/Biome-Id-Fixer/discussions/10_
This might be also an issue, so i'll post it here too.
Minecraft 1.16.5, Forge 36.2.31

**Comment by desagas** [comment]
This mod does not fix things “after the fact.” It is preventative, not retroactive. If the mod was not installed before you added biomes, adding it after will not correct it.

Please read the Curse page and the wiki for more info.

**Comment by Gargule** [comment]
I'm trying to say that client was OK before fixer was installed. And after deletion fixer from "mods" biome ID's became normal again.
Also, i'm here mostly for information about source of ID's to mod's json-file, because it's definetlty not the level.dat and i'm interested in which other place Minecraft stores ID's

**Comment by desagas** [comment]
If it was okay before installing this, and NOTHING else was installed at the same time that this was installed, then NOTHING should have went wrong. The only way something could have gone wrong is 1 of 2 senarios: 1, you forced the game to quit while it was loading, which means the json file was corrupt from the beginning, or 2, the json file was opened, and saved or autosaved in a rich text format of a text file, with the same json extension. Otherwise, I do not know of a single instance that causes this to happen.

It literally took me 72 hours, not 3 days, but 72 hours of non-stop code digging, testing thousands of tiny lines of code within minecraft to find this out. Best of luck. This mod takes the original assignments as assigned by forge or minecraft original code, and then all other mods added start going up from 1, provided another does not already have that assigned number. It them writes them to the json file, and uses that file when assigning new or checking for existing biomes.

**Comment by Gargule** [comment]
Sorry, but i'm pretty sure that wasn't any of these scenarios. And anyways, our modpack client was fucked up by yout mod. ) Anyways, i just picked ID's from level.dat and manualy fixed generated JSON with them. And then threw that json at server that somewhy was scrambled at the first place. That fixed all out problems
Fact that we got scrambled by mods only server, but not client is REALLY strange. Maybe it's some clientsided code of some mod that saved us from scramble and then messed with your mod. I can give you a modlist if you interested.

**Comment by desagas** [comment]
I think I know what may have happened. Chances are your server already had a file generated, which in this case, you should have copied that one to your local instance, as directed in the wiki for this mod. This may have caused some issues if the server loaded the biomes in a different order from what your local client did. But, this should not have scrambled the list, I am unsure what would have caused this. But, I am closing this now as I will not be investigating it any further.
